### ISSUE TITLE
Issue Installing with Packer.nvim

### ISSUE THREAD

**Issue by chr0n1x** [kunzaatko/nord.nvim#5]
my packer init block:

```lua
    use {
      'kunzaatko/nord.nvim',
      requires = { 'rktjmp/lush.nvim', opt = true },
      config = function() vim.cmd("colorscheme nord") end,
      after = { 'lush.nvim' },
    }
```

Nuked my entire `~/.local`, `~/.cache` and `~/.config/nvim` directories, started from scratch. The above seems to just fail silently.

When I try to `:colorscheme <tab>` though I see that `nord` is installed.

```
:colorscheme <tab>
blue       darkblue   default    delek      desert     elflord    evening    industry   koehler    morning    murphy     nord ...(others)
:colorscheme nord
```

 So I try `:colorscheme nord` and I get this error:
```
:colorscheme
blue       darkblue   default    delek      desert     elflord    evening    industry   koehler    morning    murphy     nord       pablo      peachpuff  ron        shine      slate      torte      zellner
Error detected while processing /Users/kran/.local/share/nvim/site/pack/packer/opt/nord.nvim/colors/nord.vim:
line    2:
E5108: Error executing lua [string ":lua"]:1: module 'nord-nvim' not found:
        no field package.preload['nord-nvim']
        no file './nord-nvim.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/nord-nvim.lua'
        no file '/usr/local/share/lua/5.1/nord-nvim.lua'
        no file '/usr/local/share/lua/5.1/nord-nvim/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nord-nvim.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nord-nvim/init.lua'
        no file '/Users/kran/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nord-nvim.lua'
        no file '/Users/kran/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nord-nvim/init.lua'
        no file '/Users/kran/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nord-nvim.lua'
        no file '/Users/kran/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nord-nvim/init.lua'
        no file './nord-nvim.so'
        no file '/usr/local/lib/lua/5.1/nord-nvim.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/nord-nvim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/kran/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nord-nvim.so'
Press ENTER or type command to continue
```

Any idea what Im doing wrong?

**Comment by kunzaatko** [comment]
Hello! Sorry for the inconvenience. Your issue is caused by the colour-spec from lush not being loaded as a plugin. It is not loaded because it is an opt plugin and it does not get loaded by packer for some reason.

I think that this must be a bug in packer, because based on your packer block, it should get loaded. I had a similar problem with gitsigns due to packer. A hack that should solve this is adding a condition to the block that evaluates to true. Try if it works (it does for me).

Your packer init block should then look like this:
```lua
    use {
      'kunzaatko/nord.nvim',
      requires = { 'rktjmp/lush.nvim' },
      config = function() vim.cmd("colorscheme nord") end,
      after = { 'lush.nvim' },
      cond = true
    }
```

I will investigate whether this is truly a bug in packer and if not, I will update the README.

Hope this works!

**Comment by chr0n1x** [comment]
@kunzaatko Thanks! That worked. I made that change, then did `:PackerInstall`, `:PackerSync` (just in case) and finally a `:PackerCompile`

**Comment by chr0n1x** [comment]
one thing to note - the steps that I detail above (installing, syncing then compiling) I believe I tried with the other config too. Hope that helps. Feel free to close if you cannot reproduce though.

**Comment by kunzaatko** [comment]
I actually did achieve to reproduce the issue you had, but I really do not know why this is happening with this packer block. In my view, the plugin with this setting should be loaded normally. Packer has a pretty good chat room, so I will try to investigate why this happens and if I get a better reason as to why it does and a better answer, I will change it in the README and ping you.
Thanks for the info!

**Comment by chr0n1x** [comment]
@kunzaatko thanks for updating, I really appreciate the help 😄

**Comment by kunzaatko** [comment]
An update about this issue @chr0n1x : The reason this plugin was not loaded was the `after` key of the block... It was explained to me by @clason:

See https://github.com/wbthomason/packer.nvim#sequencing
`after` does not __load__ `lush`; it just defers the loading of `nord` until `lush` is loaded -- which is never the case since you set it to `opt`

I will correct it in the readme.

**Comment by chr0n1x** [comment]
got it, thanks @kunzaatko !
